IMS-23: Create login view MacOS
santelizvargas/ElectronicsStoreIMS pull request #19
Opened 2024-08-02 05:31 UTC by Rexmoon

### Related ticket

Ticket: [Create login view MacOS](https://developer-solutions.atlassian.net/browse/IMS-23)

### Description

- Login view added

**Made reusable components like:**
- IMS Backgground
- IMS text field and secure field

### Medias (if needed)

https://github.com/user-attachments/assets/943c8ade-a096-46e1-9070-aff1c309069e

### Testplan

- [x] I tested this change on my local environment.
- [x] I ran the project using multiple simulators in Xcode.
- [ ] I ran the project using Real device (if applicable).
- [ ] I ran the unit tests.
- [ ] I requested this endpoint on Postman (if applicable).
- [ ] I requested this endpoint on Swagger documentation (if applicable).

### Checklist

- [ ] I added tests for this change.
- [x] I checked the code style and run the linter.
- [ ] I added necessary documentation (if applicable).

2024-08-02 19:09 UTC, santelizvargas requested changes
Please take a look and resolve conflict + git issue

2024-08-02 19:15 UTC, derian-cordoba commented
> Please take a look and resolve conflict + git issue

I can address the git issues if needed.

2024-08-02 19:20 UTC, Rexmoon commented
Sure, I'll be working on it!

2024-08-02 23:23 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +    static let secureButtonXOffset: Double = -8
I think this variable maybe renamed like `secureHorizontalOffsetButton` for following the `offset` method format (`.offset(x: number)`).

2024-08-02 23:23 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/Login/View/LoginView.swift
> +            Group {
What is the reason to use `Group` method? You only have two view elements within the Group, these elements could be declared without Group wrapper.

2024-08-02 23:23 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +            case .email: "Email"
Can you add the `password` case pls?

2024-08-03 01:28 UTC, santelizvargas commented on ims-apple/IMS Apple/Assets.xcassets/IMS Colors/imsGray.colorset/Contents.json
> +{
"We need to review and ensure that colors are not duplicated, as some were already added in previous pull requests.

2024-08-03 01:30 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/BlurCircle/BlurCircle.swift
> +    }
We can remove the marks from the properties and initializers.

```suggestion
struct BlurCircle: View {
    @State private var blurRadius: CGFloat = Constants.primaryBlur
    
    private let color: Color
    private let position: Position
    
    init(color: Color,
         position: Position) {
        self.color = color
        self.position = position
    }
```

2024-08-03 01:34 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/CustomStyles/IMSTextFieldStyle.swift
> +            )
If the background will have more than one line, we can use { } instead of ().

<img width="267" alt="image" src="https://github.com/user-attachments/assets/ee74a082-1a22-46f7-9b79-d973d3afcc2f">

2024-08-03 01:36 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +    static let secureButtonXOffset: Double = -8
Why use negative offset? only need add padding trailing to component for that because that button is in a ZStack

2024-08-03 01:36 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +
Remove extra space

2024-08-03 01:36 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +    @State private var isSecure: Bool = true
Use private and add init

2024-08-03 01:37 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +                    Image(systemName: isSecure ? "eye.slash" : "eye")
Add to constants

2024-08-03 01:38 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +    @Binding var text: String
Remove extra space and add private

2024-08-03 01:39 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +            TextField("", text: $text)
Aren't we going to use a placeholder?

2024-08-03 01:39 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/Login/View/LoginView.swift
> +            Group {
Remove unnecessary group

2024-08-03 01:40 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/Login/View/LoginView.swift
> +                }
Use custom button style

2024-08-03 04:33 UTC, Rexmoon commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +    static let secureButtonXOffset: Double = -8
Yeah I forgot change them. Thanks

2024-08-03 04:36 UTC, Rexmoon commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +            case .email: "Email"
Not here. The reason for this enum is to handle the common text fields like: Email, numbers, custom and sth else we'll need. Password filed is created in IMSSecureField.

2024-08-03 04:42 UTC, Rexmoon commented on ims-apple/IMS Apple/Assets.xcassets/IMS Colors/imsGray.colorset/Contents.json
> +{
Sure. We need to talk about that because I cannot see order when sth of us create a new color set. For example:
![Screenshot 2024-08-02 at 22 39 19](https://github.com/user-attachments/assets/91515534-bf78-44b5-9553-3886efdd5e66)
![Screenshot 2024-08-02 at 22 40 48](https://github.com/user-attachments/assets/b00a1c44-ebf3-4991-a432-0084e57a74f6)

They're normal colors but called like gradient colors? I don't know. We can create a new ticket to fix that making or using an strategy to handle.

2024-08-03 04:45 UTC, santelizvargas commented on ims-apple/IMS Apple/Assets.xcassets/IMS Colors/imsGray.colorset/Contents.json
> +{
I no remember that but I think that Diana ask to Jonathan about the name of color, and those two color only be use in gradient. You can rename the colors is needed but no add the same hexadecimal value with another name

2024-08-03 04:58 UTC, Rexmoon commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +            TextField("", text: $text)
I don't sure about it. But we have the texfields header I mean.

2024-08-03 05:05 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/Login/View/LoginView.swift
> +                }
I'll work on it.

2024-08-05 02:38 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/CustomStyles/ActionButtonStyle.swift
> +struct ActionButtonStyle: ButtonStyle {
We have a button Style for this, please reuse

2024-08-05 02:40 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/Login/View/LoginView.swift
> +
remove mark

2024-08-05 02:43 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +                    .textFieldStyle(IMSStyle())
Please need a more specific name. Because IMSStyle is a global name.
if you have a button. What name do you think?

- IMSTextFieldStyle
- IMSButtonStyle
- etc

2024-08-05 02:44 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSSecureField.swift
> +                .padding(.trailing, Constants.secureButtonTrailingPadding)
use this button like plain style. In the design we only have a eye without a background

2024-08-05 03:28 UTC, santelizvargas approved these changes

2024-08-05 03:45 UTC, merged