IMS-37 Create sales history
santelizvargas/ElectronicsStoreIMS pull request #21
Opened 2024-08-07 02:13 UTC by DianaZeledon

### Related ticket

Ticket: [IMS-37 Create sales history](https://developer-solutions.atlassian.net/browse/IMS-37)

### Description

- Created sales history view
- Created mock model

(Provide context and explain why you are making the change you are making, and why it is the right one)

### Medias (if needed)

(Provide images or videos about the changes)

### Testplan

- [X] I tested this change on my local environment.
- [X] I ran the project using multiple simulators in Xcode.
- [X] I ran the project using Real device (if applicable).
- [ ] I ran the unit tests.
- [ ] I requested this endpoint on Postman (if applicable).
- [ ] I requested this endpoint on Swagger documentation (if applicable).

### Checklist

- [ ] I added tests for this change.
- [ ] I checked the code style and run the linter.
- [ ] I added necessary documentation (if applicable).

2024-08-07 02:15 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/CustomStyles/GradientButtonStyle.swift
> +    private let imageLeft: String?
we can use "Aligment" instead right or left

2024-08-07 02:17 UTC, santelizvargas commented on ims-apple/IMS Apple/Utilities/Components/CustomStyles/GradientButtonStyle.swift
> +        .frame(height: buttonHeight)
Use same frame for height

2024-08-07 02:20 UTC, santelizvargas commented on ims-apple/IMS Apple/MockData/Models/HistoryModel.swift
> +    var id = UUID()
```suggestion
    let id: UUID = UUID()
```

2024-08-07 02:24 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +                Divider()
Use custom divider

2024-08-07 02:24 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +            .clipShape(RoundedRectangle(cornerRadius: HistoryConstants.cornerRadius))
Use same shape for background

2024-08-07 02:25 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +                                                 buttonHeight: HistoryConstants.Button.height,
Im not sure about that, we can use the button size

2024-08-07 02:32 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +                        .foregroundStyle(.blue)
```suggestion
                    Button { 
                        // Do something
                    } label: {
                        Text("Ver Factura")
                    }
                        .underline()
                        .buttonStyle(.plain)
                        .foregroundStyle(.blue)
```

2024-08-07 02:46 UTC, Rexmoon commented on ims-apple/IMS Apple/MockData/Models/HistoryModel.swift
> +    var id = UUID()
It will be a convection @santelizvargas ?

2024-08-07 02:47 UTC, Rexmoon commented on ims-apple/IMS Apple/MockData/Models/HistoryModel.swift
> +extension HistoryModel {
Can we use MARKs for extensions please?

2024-08-07 02:49 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +//  Created by Diana Zeledon on 5/8/24.
Change to Brandon Santeliz @santelizvargas  🤔 ?

2024-08-07 02:54 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +private enum HistoryConstants {
Why it not called just like **Constants**?

A constants private enum by file so I think its redundant.

2024-08-07 02:56 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +//  Created by Diana Zeledon on 5/8/24.
No problem, we going to change later.

2024-08-07 02:56 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +    enum Button {
Enum inside another enum?

I do not know but we can add two variables and call them like:

**buttonheight and button cornerRadius**

2024-08-07 03:00 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +    enum Button {
https://ashley-oldham.medium.com/avoiding-magic-numbers-7f2721b20402

2024-08-07 03:04 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +        LazyVGrid(columns: columns) {
I think is not neccessary LazyVGrid to static content.

2024-08-08 01:55 UTC, santelizvargas requested changes
Remember add another button

2024-08-10 02:54 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +    private let columns: [GridItem] = Array(repeating: GridItem(), count: Constants.columnsNumber)
Remove unnecesary columns var

2024-08-10 02:59 UTC, santelizvargas commented on ims-apple/IMS Apple/Views/History/SalesHistoryView.swift
> +    private var pageButtons: some View {
Add mark after all marks

2024-08-10 03:02 UTC, santelizvargas approved these changes

2024-08-10 03:05 UTC, DerianCordobaPerez approved these changes

2024-08-10 03:05 UTC, merged