IMS-48 Created invoice sale view
santelizvargas/ElectronicsStoreIMS pull request #33
Opened 2024-08-13 03:40 UTC by DianaZeledon

### Related ticket

Ticket: [IMS-48 Created invoice sale view](https://developer-solutions.atlassian.net/browse/IMS-48)

### Description

- Create invoice sale view
- Modified textfield component
- Added colors for gradient buttons

![Screenshot 2024-08-12 at 9 37 43 PM](https://github.com/user-attachments/assets/f0e73ff4-aec7-44e2-9227-e2fec15a1b95)

(Provide context and explain why you are making the change you are making, and why it is the right one)

### Medias (if needed)

(Provide images or videos about the changes)

### Testplan

- [X] I tested this change on my local environment.
- [X] I ran the project using multiple simulators in Xcode.
- [X] I ran the project using Real device (if applicable).
- [ ] I ran the unit tests.
- [ ] I requested this endpoint on Postman (if applicable).
- [ ] I requested this endpoint on Swagger documentation (if applicable).

### Checklist

- [ ] I added tests for this change.
- [ ] I checked the code style and run the linter.
- [ ] I added necessary documentation (if applicable).

2024-08-13 03:47 UTC, Rexmoon requested changes

2024-08-13 03:47 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +//  Created by Diana Zeledon on 12/8/24.
Change for Brandon's name

2024-08-13 03:47 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +    @State private var totalValue = ""
Add String typing

2024-08-13 03:47 UTC, Rexmoon commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +                .buttonStyle(GradientButtonStyle(imageLeft: "eye",
Image names can stay in constants

2024-08-14 02:01 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +    @State private var totalValue = ""
I agree, if we add the type in the variable declaration, we will improve the compile time.
https://danielchasehooper.com/posts/why-swift-is-slow/

2024-08-14 02:05 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +    @State private var totalValue = ""
```suggestion
    @State private var nameValue: String = ""
    @State private var phoneNumberValue: String = ""
    @State private var quantityValue: String = ""
    @State private var descriptionValue: String = ""
    @State private var priceValue: String = ""
    @State private var totalValue: String = ""
```

2024-08-14 02:08 UTC, DianaZeledon commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +                .buttonStyle(GradientButtonStyle(imageLeft: "eye",
@Rexmoon Those are not the image name, they are the text at the top of the text field. Would it still be good to add them to constants?

2024-08-14 02:11 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +    private var hasBorder: Bool
Can you change this variable for let pls?

```suggestion
    private let hasBorder: Bool
```

2024-08-14 02:13 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Utilities/Components/IMSTextField/IMSTextField.swift
> +    static let cornerRadius: CGFloat = 8
I think a better name might be `cornerRadiusSize` because it is more declarative.

```suggestion
    static let cornerRadiusSize: CGFloat = 8
```

2024-08-14 02:14 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +    static let cornerRadius: CGFloat = 12
Same here.
https://github.com/santelizvargas/ElectronicsStoreIMS/pull/33/files#r1716225081

2024-08-14 02:16 UTC, DerianCordobaPerez commented on ims-apple/IMS Apple/Views/InvoiceSale/InvoiceSaleView.swift
> +    static let spacing: CGFloat = 30
The name maybe improved, like `spacingSize`.

2024-08-14 02:25 UTC, DerianCordobaPerez approved these changes

2024-08-14 02:31 UTC, santelizvargas approved these changes
LGTM 👍

2024-08-14 02:35 UTC, Rexmoon approved these changes

2024-08-14 02:36 UTC, merged